name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: swift-actions/setup-swift@v1.24.0
        name: Setup Swift
        with:
          swift-version: "5.8"

      - name: Install dependencies
        run: |
          sudo apt install libzstd-dev libcurl4-openssl-dev libsasl2-dev

      - name: Fetch librdkafka
        run: git submodule update --init

      - uses: actions/cache@v3
        with:
          path: .build
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-
             
      - name: Build
        run: swift build

      - name: Start single node kafka cluster
        run: |
          sudo docker-compose up -d

      - name: Run tests
        run: swift test

      - run: docker-compose down
