name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: swift-actions/setup-swift@v1.23.0
        name: Setup Swift
        with:
          swift-version: "5.8"

      - name: Fetch librdkafka
        run: git submodules update --init
             
      - name: Build
        run: swift build
