name: swiftlint

on:
  pull_request:
    paths:
      - '.github/workflows/swiftlint.yaml'
      - '.swiftlint.yml'
      - '**/*.swift'

jobs:
  swiftlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: .build
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-

      - name: Lint
        uses: norio-nomura/action-swiftlint@3.2.1
